# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RBFKernel <- function(y, xIn, h) {
    .Call('_VBfuns_RBFKernel', PACKAGE = 'VBfuns', y, xIn, h)
}

vbetelMatrixCalculations <- function(g, hessian, lambdaHat, exponent, dgdt) {
    .Call('_VBfuns_vbetelMatrixCalculations', PACKAGE = 'VBfuns', g, hessian, lambdaHat, exponent, dgdt)
}

