# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluates and differentiates the RBF Kernel.
#' 
#' This function returns a list of the value of the RBF Kernel, and gradient with respect to the second argument, of the RBF Kernel.
#' @param y Vector of inputs that are not differentiated.
#' @param xIn N * 1 matrix of inputs that are differentiated.
#' @param h Smoothing parameter.
RBFKernel <- function(y, xIn, h) {
    .Call('_VBfuns_RBFKernel', PACKAGE = 'VBfuns', y, xIn, h)
}

#' Shuffles a low discrepancy sequence in the unit hypercube from Randomised Quasi-Monte-Carlo (RQMC)
#' 
#' This function randomly shuffles a sequence of low star discrepancy numbers in a way that preserves the low discrepancy properties according to the Scrambled Net of Matousek (1998).
#' This step is essential for RQMC, where the same low discrepancy numbers can be shuffled each iteration to induce a Central Limit Theorem and other beneficial randomness properties to the approximation
#' @param sequence an N x D matrix of N low discrepancy numbers from the D dimensional unit hypercube. Each entry should be between zero and one.
shuffleRQMC <- function(sequence) {
    .Call('_VBfuns_shuffleRQMC', PACKAGE = 'VBfuns', sequence)
}

#' Generate N draws from the D dimensional unit hypercube according to a Sobol Sequence
#' 
#' This function provides a N x D low discrepancy sequence of numbers for Quasi-Monte-Carlo
#' @param N Number of draws
#' @param D Dimension of draws
#' @param skip Start draws from the skip + 1'th iteration of the Sobol Sequence
#' @param fileLocation Location of a file containing the Sobol Sequence direction numbers
sobolPoints <- function(N, D, skip, fileLocation) {
    .Call('_VBfuns_sobolPoints', PACKAGE = 'VBfuns', N, D, skip, fileLocation)
}

#' Returns the derivative of the log-joint distribution with respect to theta for VBETEL
#' 
#' Given the intermediate inputs, this function calculates the last few stages of the derivative of the logjoint with respect to theta.
#' @param g An N x D matrix where rows correspond to the D dimensional moment condition evaluated at each of the N observations.
#' @param hessian The D x D matrix of the hessian matrix of h(theta, lambda), usually provided by nlm(...)$hessian.
#' @param lambdaHat A D dimensional vector of the optimal lambda values.
#' @param exponent An N dimensional vector of exp(lambdaHat * g) evaluated at each of the N observations
#' @param gdt A D x P x N array of the D x P matrix of the derivative of g (D dimensional) with respect to theta (P dimensional), 
#' each slice corresponds to the derivative matrix for one observation
#' @export
vbetelMatrixCalculations <- function(g, hessian, lambdaHat, exponent, dgdt) {
    .Call('_VBfuns_vbetelMatrixCalculations', PACKAGE = 'VBfuns', g, hessian, lambdaHat, exponent, dgdt)
}

